exports.seed = (knex) =>
  // Deletes ALL existing entries
  knex('pessoa').del()
    .then(() =>
      // Inserts seed entries
      knex('pessoa').insert([
        {
          nome: 'danielson de oliveira tavares',
          nascimento: '29/03/1984',
          sexo: 'M',
          email: 'caosdan@gmail.com',
          ddd_fixo: '21',
          tel_fixo: '22221111',
          ddd_cel: '21',
          tel_cel: '933334444',
          cep: '24420280',
          tipo_logradouro: 'avenida',
          logradouro: 'jose mendonça de campos',
          numero_logradouro: '720',
          complemento: 'bloco 4, apartamento 201',
          bairro: 'colubande',
          cidade: 'são gonçalo',
          uf: 'RJ',
          cpf: '10673723412',
          rg: '123456789',
        },
        {
          nome: 'Liz Teresinha Duarte',
          cpf: '55973972143',
          rg: '247462305',
          nascimento: '05/05/1974',
          sexo: 'F',
          email: 'lizteresinha@greenschool.com.br',
          cep: '91160810',
          tipo_logradouro: 'Rua',
          logradouro: 'Mil Novecentos e Noventa e Dois',
          complemento: '',
          numero_logradouro: 940,
          bairro: 'Rubem Berta',
          cidade: 'Porto Alegre',
          uf: 'RS',
          ddd_fixo: '51',
          tel_fixo: '28617003',
          ddd_cel: '51',
          tel_cel: '986010574',
        },
        {
          nome: 'Emily Sandra Mendes',
          cpf: '95856598750',
          rg: '495644596',
          nascimento: '12/07/1970',
          sexo: 'F',
          email: 'eemilysandramendes@lojascentrodamoda.com.br',
          cep: '24451380',
          tipo_logradouro: 'Rua',
          logradouro: 'Heleno Ramos',
          numero_logradouro: 194,
          bairro: 'Colubande',
          cidade: 'São Gonçalo',
          uf: 'RJ',
          ddd_fixo: '21',
          tel_fixo: '39832262',
          ddd_cel: '21',
          tel_cel: '985253104',
        },
        {
          nome: 'Beatriz Maya Silva',
          cpf: '38353764709',
          rg: '177727354',
          nascimento: '09/07/1970',
          sexo: 'F',
          email: 'bbeatrizmayasilva@profiledesign.com.br',
          cep: '24431090',
          tipo_logradouro: 'Travessa',
          logradouro: 'Quintino',
          numero_logradouro: 515,
          bairro: 'Gradim',
          cidade: 'São Gonçalo',
          uf: 'RJ',
          ddd_fixo: '21',
          tel_fixo: '38551116',
          ddd_cel: '21',
          tel_cel: '993531384',
        },
        {
          nome: 'Valentina Lúcia Brito',
          cpf: '44497636704',
          rg: '117472293',
          nascimento: '02/05/1966',
          sexo: 'F',
          email: 'valentinaluciabrito__valentinaluciabrito@googlemail.com',
          cep: '24722385',
          tipo_logradouro: 'Rua',
          logradouro: 'Padre José de Anchieta',
          numero_logradouro: 409,
          bairro: 'Santa Luzia',
          cidade: 'São Gonçalo',
          uf: 'RJ',
          ddd_fixo: '21',
          tel_fixo: '28075468',
          ddd_cel: '21',
          tel_cel: '994909550',
        },
        {
          nome: 'Ryan Benedito Figueiredo',
          cpf: '40241196728',
          rg: '193900099',
          nascimento: '07/02/1958',
          sexo: 'M',
          email: 'rryanbeneditofigueiredo@decorsul.com',
          cep: '24445495',
          tipo_logradouro: 'Rua',
          logradouro: 'General Antônio Rodrigues',
          numero_logradouro: 525,
          bairro: 'Centro',
          cidade: 'São Gonçalo',
          uf: 'RJ',
          ddd_fixo: '21',
          tel_fixo: '28111422',
          ddd_cel: '21',
          tel_cel: '992555527',
        },
        {
          nome: 'Mirella Vanessa Raquel dos Santos',
          cpf: '41296859703',
          rg: '326412682',
          nascimento: '12/09/1951',
          sexo: 'F',
          email: 'mirellavanessaraqueldossantos_@brf-br.com',
          cep: '24471260',
          tipo_logradouro: 'Rua',
          logradouro: 'Alzira P. Magalhães',
          numero_logradouro: 190,
          bairro: 'Itaoca',
          cidade: 'São Gonçalo',
          uf: 'RJ',
          ddd_fixo: '21',
          tel_fixo: '28822825',
          ddd_cel: '21',
          tel_cel: '997763740',
        },

      ]));
